# Generated by Django 4.0.4 on 2022-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='visits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
