# Generated by Django 4.0.4 on 2022-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_links_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
